# Generated by Django 5.2.5 on 2025-08-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='referrer',
            new_name='referred_by',
        ),
    ]
