# Generated by Django 5.2.5 on 2025-08-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
