# Generated by Django 5.2.5 on 2025-08-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0006_deposit_approved_at_deposit_status_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10, null=True),
        ),
    ]
